<?php

namespace AppBundle\Repository;

/**
 * AspectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AspectRepository extends \Doctrine\ORM\EntityRepository
{
}
