<?php

namespace AppBundle\Repository;

/**
 * StuntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuntRepository extends \Doctrine\ORM\EntityRepository
{
}
