<?php

namespace AppBundle\Repository\Model;

/**
 * ExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraRepository extends \Doctrine\ORM\EntityRepository
{
}
